# **1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?**

**Ans :- ** NumPy, short for Numerical Python, is a fundamental library in the Python ecosystem for scientific computing and data analysis. Its purpose and advantages can be summarized as follows:

**Purpose of NumPy**

Efficient Numerical Operations: NumPy provides support for large, multi-dimensional arrays and matrices of numeric data. It allows for efficient operations on these arrays, enabling complex mathematical computations with high performance.

**Mathematical Functions:**
 It includes a wide range of mathematical functions that operate element-wise on arrays, such as trigonometric functions, statistical operations, and linear algebra routines.

**Integration with Other Libraries:**
 NumPy serves as the foundational library for other scientific computing libraries in Python, such as SciPy, Pandas, and scikit-learn, by providing the underlying data structures and operations needed.

**Advantages of NumPy Performance:**

 NumPy's arrays are implemented in C and Fortran, which means operations on NumPy arrays are significantly faster than equivalent operations on Python lists. This is because NumPy uses contiguous blocks of memory and vectorized operations, which can be executed in parallel by modern processors.

**Memory Efficiency:**

 NumPy arrays consume less memory compared to Python lists because they are of fixed size and type. This allows for efficient storage and manipulation of large datasets.

**Broadcasting:**

NumPy supports broadcasting, which enables operations on arrays of different shapes and sizes without the need for explicit loops. This leads to cleaner and more efficient code.

**Vectorization:**

 Operations in NumPy are vectorized, meaning that they are performed on entire arrays rather than individual elements. This makes code more concise and faster by leveraging optimized low-level implementations.

**Convenient Syntax:**

NumPy provides a rich set of functions and methods for numerical computing, which simplifies many tasks that would be more cumbersome with basic Python lists and loops.

**Advanced Indexing and Slicing:**
 NumPy offers powerful indexing and slicing capabilities, allowing for sophisticated manipulation and querying of array data.

**Interoperability:**

 NumPy arrays are compatible with a wide range of other libraries and tools, making it easier to integrate with other parts of the scientific Python stack and external software.

**Mathematical Routines:**

It provides a comprehensive suite of mathematical routines, including linear algebra operations, Fourier transforms, and random number generation, which are crucial for scientific computing and data analysis.

**How NumPy Enhances Python’s Capabilities Speed:**

 By using low-level implementations, NumPy performs numerical operations much faster than native Python lists. This speed is crucial for handling large datasets and performing complex calculations.

**Ease of Use:**

NumPy’s high-level abstractions, such as array operations and mathematical functions, make it easier to write and understand code for scientific computing. This reduces development time and potential for errors.

**Scalability:**

 NumPy arrays scale well with data size and complexity, making it possible to work with large datasets that would be impractical to handle with pure Python structures.

**Community and Ecosystem:**

NumPy is well-integrated into the scientific Python ecosystem, meaning it benefits from a large community, extensive documentation, and compatibility with many other scientific libraries and tools.

**In summary,** NumPy significantly enhances Python's capabilities for numerical operations by providing a high-performance, memory-efficient, and feature-rich framework for working with arrays and matrices. This makes it an indispensable tool for scientific computing and data analysis.





# **2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?**

**Ans:-** Both **np.mean()** and **np.average()** are functions in NumPy used to calculate averages, but they have different features and use cases. Here’s a detailed comparison:


### **np.mean()**
**Purpose:**   Computes the arithmetic mean of the array elements.

**Usage:**

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)
print(mean_value)  # Output: 3.0


3.0


**Key Characteristics:**

**Simplicity:** np.mean() simply computes the average by summing all elements and dividing by the number of elements.

**Performance:** It is optimized for performance and is generally faster for straightforward mean calculations.

**When to Use:**

When you need to calculate the arithmetic mean of a dataset.
When you don’t need to account for different weights for the data points.

### **np.average()**

**Purpose:** Computes the weighted average of the array elements, or the arithmetic mean if no weights are provided.

**Usage:**

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
average_value = np.average(arr)
print(average_value)  # Output: 3.0

# With weights
weights = np.array([1, 1, 1, 1, 1])
weighted_average = np.average(arr, weights=weights)
print(weighted_average)  # Output: 3.0

weights = np.array([1, 2, 3, 4, 5])
weighted_average = np.average(arr, weights=weights)
print(weighted_average)  # Output: 3.6666666666666665


3.0
3.0
3.6666666666666665


**Key Characteristics:**

**Weights:** np.average() allows for weighted averaging, where each element’s contribution to the average can be scaled by a weight.

**Flexibility:** You can specify weights using the weights parameter, making it more versatile in situations where some data points should contribute more to the average than others.

**Return Type:**
 Returns the weighted average when weights are provided; otherwise, it behaves like np.mean().

**When to Use:**

When you need to compute a weighted average where different elements contribute differently to the final average.

When you want the flexibility to provide weights or additional parameters like returned for more complex averaging scenarios.

**Summary**

* np.mean() is a straightforward function for calculating the arithmetic mean of an array and is generally preferred when no weights are involved.
* np.average() offers more functionality, including the option to compute a weighted average. Use this when you need to consider the relative importance of different elements or when you require additional flexibility.

In practice, if you only need to compute the average of an array of numbers with equal importance, np.mean() is simpler and faster. If you need to apply weights or require more advanced averaging capabilities, np.average() is the appropriate choice.

# **3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D rarays.**

**Ans:-** Reversing a NumPy array along different axes can be useful for various tasks, such as data manipulation or preparing data for machine learning. Here's how you can reverse NumPy arrays along different axes, with examples for both 1D and 2D arrays.

## **Reversing a 1D Array**

For a 1D array, reversing is straightforward. You can use slicing to reverse the order of elements.

Example:

In [3]:
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_arr_1d = arr_1d[::-1]

print("Original 1D array:", arr_1d)
print("Reversed 1D array:", reversed_arr_1d)


Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]


## **Reversing a 2D Array**
For a 2D array, you might want to reverse along specific axes:

* Reverse along rows (axis=0): Flips the array vertically.
* Reverse along columns (axis=1): Flips the array horizontally.

Example:

In [4]:
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original 2D array:\n", arr_2d)

# Reverse along rows (axis=0)
reversed_rows = arr_2d[::-1, :]
print("Reversed along rows (axis=0):\n", reversed_rows)

# Reverse along columns (axis=1)
reversed_columns = arr_2d[:, ::-1]
print("Reversed along columns (axis=1):\n", reversed_columns)

# Reverse along both axes
reversed_both = arr_2d[::-1, ::-1]
print("Reversed along both axes:\n", reversed_both)


Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed along rows (axis=0):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed along columns (axis=1):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Reversed along both axes:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


**Explanation:**

* Reversing along rows (axis=0): arr_2d[::-1, :] reverses the order of rows while keeping the columns in their original order.
* Reversing along columns (axis=1): arr_2d[:, ::-1] reverses the order of columns while keeping the rows in their original order.
* Reversing along both axes: arr_2d[::-1, ::-1] reverses the array both horizontally and vertically.

These slicing operations provide a flexible and powerful way to manipulate and rearrange array data in NumPy.

# **4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.**

**Ans:-**In NumPy, determining the data type of elements in an array is straightforward and crucial for efficient memory management and performance. Here's how you can determine the data type and why it matters:

**Determining the Data Type**

You can use the .dtype attribute of a NumPy array to determine its data type.

Example:

In [5]:
import numpy as np

# Create arrays with different data types
arr_int = np.array([1, 2, 3, 4])
arr_float = np.array([1.0, 2.0, 3.0, 4.0])
arr_complex = np.array([1+2j, 3+4j])

# Print the data types
print("Data type of arr_int:", arr_int.dtype)
print("Data type of arr_float:", arr_float.dtype)
print("Data type of arr_complex:", arr_complex.dtype)


Data type of arr_int: int64
Data type of arr_float: float64
Data type of arr_complex: complex128


## Importance of Data Types

**1.Memory** **Management**:

* **Efficient Storage:** Different data types require different amounts of memory. For instance, np.float64 (64-bit floating point) uses more memory than np.float32 (32-bit floating point). Choosing the appropriate data type can help manage memory usage efficiently, especially when working with large datasets.
* **Data Type Precision:** The choice of data type affects precision. For example, using np.float32 instead of np.float64 reduces precision but also reduces memory consumption. This trade-off needs to be considered based on the requirements of the task.

**2.Performance:**

* **Computational Speed:** Operations on arrays with smaller data types (like np.float32 or np.int32) can be faster due to less data being processed and transferred. However, this might come at the cost of precision. Operations on np.float64 are generally more accurate but can be slower.
* **Hardware Compatibility:** Certain hardware, like GPUs, might be optimized for specific data types. For example, GPUs often have special support for single-precision floating-point operations (np.float32), which can lead to performance gains.

**3.Compatibility and Interoperability:**

* **Consistency:** Ensuring that all arrays in computations have compatible data types prevents unexpected results and errors. For example, mixing np.int32 with np.float64 can lead to type promotion and potential loss of precision.
* **Integration:** When working with other libraries or systems (e.g., interfacing with C/C++ code or using machine learning frameworks), data type consistency is crucial for seamless integration and data exchange.

**Summary**
* Use the .dtype attribute to determine the data type of elements in a NumPy array.
*Memory Management: Choosing the correct data type is essential for efficient memory usage. Smaller data types use less memory but might offer less precision.
*Performance: Data types impact computational speed and performance. The choice between precision and performance should be based on the specific needs of the application.
*Compatibility: Consistent data types ensure compatibility and prevent issues during data processing or when interfacing with other systems.

Choosing the right data type is crucial in optimizing both memory usage and performance, especially in large-scale data analysis and scientific computing tasks.

# **5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?**

**Ans**:- **ndarray** stands for **"n-dimensional array,"** and it is the core data structure provided by NumPy for handling large and multi-dimensional arrays of data. Here’s a detailed overview of ndarray and how it compares to standard Python lists:

**Defining ndarray**

An ndarray is a central data structure in NumPy that represents a grid of values, all of the same type, indexed by a tuple of non-negative integers. The ndarray can be one-dimensional (like a list), two-dimensional (like a matrix), or n-dimensional (like a tensor).

Creating an ndarray Example:

In [9]:
import numpy as np

# Create a 1D ndarray
arr_1d = np.array([1, 2, 3, 4, 5])

# Create a 2D ndarray
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Create a 3D ndarray
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

1
2
3


**Key Features of ndarray**

**1.Multi-dimensional:**

 ndarray supports multiple dimensions (axes), allowing for efficient manipulation of data in various shapes. This makes it suitable for tasks ranging from simple arrays to complex data structures like tensors in machine learning.

**2.Homogeneous Data Type:**

 All elements in an ndarray must be of the same data type (e.g., integers, floats). This uniformity allows NumPy to optimize memory usage and computation.

**3.Shape and Size:**

 The ndarray has an attribute .shape that returns a tuple representing the size of each dimension. For example, an array with shape (3, 4) has 3 rows and 4 columns.

**4.Vectorized Operations:**

 NumPy supports vectorized operations, meaning that operations are applied element-wise across arrays without explicit loops, resulting in faster computations.

**5.Broadcasting**:

 ndarray supports broadcasting, which allows for operations between arrays of different shapes in a flexible and efficient manner.

**6.Efficient Memory Management:**

 NumPy arrays are implemented in C and Fortran, making them more memory-efficient and faster compared to Python lists. They use contiguous blocks of memory, which allows for faster access and manipulation.

**7.Indexing and Slicing:**

 ndarray provides powerful and flexible indexing and slicing capabilities, including advanced indexing and boolean indexing.

**8.Mathematical Functions:**

 NumPy provides a wide range of mathematical functions that operate on ndarray objects, including linear algebra routines, Fourier transforms, and statistical functions.

**Differences Between ndarray and Python Lists**

**1.Homogeneity vs. Heterogeneity:**

* Python Lists: Can store elements of different types (e.g., integers, strings, lists).
* ndarray: All elements must be of the same type.

**2.Performance:**

* Python Lists: Operations on lists, especially with large data, can be slow because they require explicit loops and are not optimized for numerical operations.
* ndarray: Optimized for performance with support for vectorized operations, making numerical computations faster and more efficient.

**3Memory Usage:**

* Python Lists: More memory overhead due to additional information stored with each element.
* ndarray: Uses less memory by storing data in contiguous blocks and only requiring a single type.

**4.Multi-dimensional Capability:**

* Python Lists: Can be nested to create multi-dimensional structures, but this is not as efficient or straightforward as using NumPy arrays.
* ndarray: Directly supports multi-dimensional arrays with efficient operations.

**5.Mathematical Operations:**

* Python Lists: Do not support element-wise mathematical operations natively.
ndarray: Supports element-wise operations, linear algebra operations, and a wide array of mathematical functions.

**6.Shape and Size Attributes:**

* Python Lists: Do not have built-in attributes for shape and size.
* ndarray: Has attributes like .shape, .ndim, and .size that provide detailed information about the array's dimensions and size.

**Summary**

ndarray in NumPy is a powerful and efficient multi-dimensional array object that is designed for numerical and scientific computing. Its key features include homogeneous data types, multi-dimensional support, vectorized operations, and efficient memory management. These features make ndarray significantly more efficient and flexible than standard Python lists, especially for numerical and large-scale data processing tasks.

# **6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations**

**Ans:-** NumPy arrays provide substantial performance benefits over Python lists for large-scale numerical operations. These advantages stem from several factors related to memory management, computational efficiency, and optimized implementations. Here’s a detailed analysis of why NumPy arrays are preferred for large-scale numerical operations:

**Performance Benefits of NumPy Arrays**

**1.Efficient Memory Usage:**

* **Contiguous Memory Allocation:** NumPy arrays use contiguous blocks of memory, which reduces overhead and fragmentation compared to Python lists, where each element can be a separate object with additional metadata.
* **Homogeneous Data Types:** NumPy arrays store elements of the same data type, allowing for compact, uniform storage. This avoids the overhead associated with storing different types  type-checking that Python lists handle.

**2.Vectorized Operations:**

* **Element-wise Operations:** NumPy supports vectorized operations, where operations are performed element-wise directly on arrays. This eliminates the need for explicit Python loops, which can be slow due to Python's dynamic typing and interpreter overhead.

* **Optimized Computations:** NumPy operations are implemented in compiled C and Fortran code, which can leverage low-level optimizations and hardware acceleration (e.g., SIMD instructions), resulting in significant speedups for mathematical computations.

**3.Broadcasting:**

* **Efficient Handling of Different Shapes:** NumPy’s broadcasting mechanism allows arrays of different shapes to be used together in operations without explicit looping or reshaping. This avoids unnecessary data duplication and manipulation, improving performance and memory efficiency.

**4.Reduced Overhead:**

* **Fixed Data Types:** Unlike Python lists, which store objects with overhead, NumPy arrays store data in a single, contiguous block with a fixed data type. This reduces memory overhead and improves access speed.
* **Optimized Algorithms:** Many mathematical functions and operations in NumPy are implemented using highly optimized algorithms tailored for performance, leveraging efficient numerical libraries like BLAS and LAPACK.

**5.Parallelization and Hardware Utilization:**

* **Parallel Processing:** NumPy operations can be parallelized to take advantage of multi-core processors and vectorized hardware instructions, speeding up computations significantly.
* **Integration with Libraries:** NumPy is designed to work well with other scientific libraries that can further optimize computations, such as those leveraging GPU acceleration (e.g., CuPy).

**6.Advanced Indexing and Slicing:**

**Efficient Data Manipulation:** NumPy’s advanced indexing and slicing mechanisms allow for efficient extraction and manipulation of array elements without the need for explicit loops or complex data structures, which can be slow with Python lists.
##**Comparison with Python Lists**

**1. Memory and Performance:**

* Python Lists: Each element in a Python list is a separate object with additional overhead. Lists are dynamically typed, meaning operations on lists involve frequent type-checking and method calls, which add to the performance cost.
* NumPy Arrays: Arrays use contiguous memory blocks and fixed data types, allowing for faster access and manipulation. Operations are performed in compiled code, which is much faster than Python's interpreted operations.

**2. Computational Efficiency:**

* Python Lists: Operations such as element-wise additions or multiplications require explicit loops in Python, which are slow compared to NumPy’s optimized, vectorized operations.
* NumPy Arrays: Operations are vectorized, reducing the need for explicit looping and enabling faster execution through low-level optimizations.

**3. Scaling:**

* Python Lists: Performance degrades with the size of the list, particularly for numerical computations that require complex operations or large-scale data handling.
* NumPy Arrays: NumPy arrays scale efficiently with data size, thanks to their optimized memory usage and computational efficiency. They handle large datasets and complex operations with ease.

Example

Here’s a simple example comparing the performance of NumPy arrays and Python lists for element-wise addition:

**Python Lists:**

In [10]:
import time

# Create two large lists
list1 = list(range(1000000))
list2 = list(range(1000000))

# Measure time for element-wise addition
start_time = time.time()
result = [x + y for x, y in zip(list1, list2)]
end_time = time.time()

print("Python list addition time:", end_time - start_time)


Python list addition time: 0.159132719039917


**Numpy array:-**

In [11]:
import numpy as np
import time

# Create two large numpy arrays
arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

# Measure time for element-wise addition
start_time = time.time()
result = arr1 + arr2
end_time = time.time()

print("NumPy array addition time:", end_time - start_time)


NumPy array addition time: 0.010310888290405273


In this example, NumPy’s performance is significantly better than Python lists due to its efficient memory usage, vectorized operations, and optimized implementation.

# **7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output**

**Ans:-**In NumPy, vstack() and hstack() are functions used to stack arrays along different axes. Here's a detailed comparison of these functions, along with examples demonstrating their usage and output.

**np.vstack()**
Purpose: Stacks arrays vertically (along the rows). It combines arrays along the first axis (axis=0), resulting in an array where the second axis (columns) remains the same, and the arrays are appended row-wise.

Usage:



In [12]:
import numpy as np

# Create some sample arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Stack arrays vertically
vstack_result = np.vstack((arr1, arr2))

print("Result of np.vstack:")
print(vstack_result)


Result of np.vstack:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**np.hstack()**

Purpose: Stacks arrays horizontally (along the columns). It combines arrays along the second axis (axis=1), resulting in an array where the first axis (rows) remains the same, and the arrays are appended column-wise.

Usage:

In [13]:
import numpy as np

# Create some sample arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])

# Stack arrays horizontally
hstack_result = np.hstack((arr1, arr2))

print("Result of np.hstack:")
print(hstack_result)


Result of np.hstack:
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


**Key Differences**

**1.Axis of Stacking:**

* vstack(): Stacks along the first axis (axis=0), so it adds rows to the existing rows.
* hstack(): Stacks along the second axis (axis=1), so it adds columns to the existing columns.

**2.Dimensional Compatibility:**

* vstack(): The arrays must have the same number of columns (i.e., the same shape along axis=1).
* hstack(): The arrays must have the same number of rows (i.e., the same shape along axis=0).

**3.Application:**

* vstack(): Used when you want to combine arrays row-wise, for example, when appending more data points to a dataset.
* hstack(): Used when you want to combine arrays column-wise, for example, when adding new features to a dataset.

**4.Examples in Context**

* Example with vstack(): Combining multiple batches of data where each batch has the same number of features (columns).

* Example with hstack(): Combining data from different sensors or features where each array has the same number of observations (rows).

**Summary**

np.vstack(): Stacks arrays vertically (adds rows). Use it when you want to combine arrays along rows.
np.hstack(): Stacks arrays horizontally (adds columns). Use it when you want to combine arrays along columns.

**8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.**

Ans:- In NumPy, fliplr() and flipud() are methods used to reverse the order of elements along specific dimensions of arrays. They are particularly useful for flipping arrays horizontally or vertically. Here’s a detailed explanation of each method and their effects on arrays of different dimensions:

## **np.fliplr()**

Purpose: Flips an array left-to-right (i.e., reverses the order of columns).

Usage:

In [14]:
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flip array left-to-right
fliplr_result = np.fliplr(arr_2d)

print("Result of np.fliplr:")
print(fliplr_result)


Result of np.fliplr:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


**Effect:**

* 2D Arrays: Reverses the order of columns for each row. In the example, the columns of the original array are flipped to appear in the reverse order.
* 1D Arrays: Not applicable, as fliplr() is intended for 2D arrays.
* 3D Arrays: Applies to the last two dimensions. For example, if you have a 3D array, fliplr() will flip the elements along the second dimension (columns) for each 2D slice.

## **np.flipud()**

Purpose: Flips an array up-to-down (i.e., reverses the order of rows).

Usage:

In [15]:
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flip array up-to-down
flipud_result = np.flipud(arr_2d)

print("Result of np.flipud:")
print(flipud_result)


Result of np.flipud:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


**Effect:**

* 2D Arrays: Reverses the order of rows. In the example, the rows of the original array are flipped to appear in the reverse order.
* 1D Arrays: Flipping a 1D array up-to-down is equivalent to reversing the array.
* 3D Arrays: Applies to the first dimension. For each 2D slice in a 3D array, flipud() will reverse the order of the rows.

**Comparison of fliplr() and flipud()**

**1.Dimensional Effect:**

* fliplr(): Affects the columns of a 2D array. It reverses the order of elements along the horizontal axis.
* flipud(): Affects the rows of a 2D array. It reverses the order of elements along the vertical axis.

**Effect on 1D Arrays:**

* fliplr(): Not defined for 1D arrays.
*flipud(): Reverses the 1D array, similar to using arr[::-1].

**Effect on 3D Arrays:**

* fliplr(): Flips each 2D slice along the horizontal axis (last two dimensions).
* flipud(): Flips each 2D slice along the vertical axis (first dimension).

**Examples**

**1D Array:**

In [16]:
arr_1d = np.array([1, 2, 3, 4, 5])

# Flipping horizontally (fliplr) is not defined for 1D arrays
# Flipping vertically (flipud) reverses the array
flipud_result = np.flipud(arr_1d)
print("Result of np.flipud on 1D array:", flipud_result)


Result of np.flipud on 1D array: [5 4 3 2 1]


**3D Array:**

In [17]:
arr_3d = np.array([[[1, 2],
                    [3, 4]],
                   [[5, 6],
                    [7, 8]],
                   [[9, 10],
                    [11, 12]]])

# Flip left-to-right
fliplr_result = np.fliplr(arr_3d)
print("Result of np.fliplr on 3D array:")
print(fliplr_result)

# Flip up-to-down
flipud_result = np.flipud(arr_3d)
print("Result of np.flipud on 3D array:")
print(flipud_result)


Result of np.fliplr on 3D array:
[[[ 3  4]
  [ 1  2]]

 [[ 7  8]
  [ 5  6]]

 [[11 12]
  [ 9 10]]]
Result of np.flipud on 3D array:
[[[ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]]

 [[ 1  2]
  [ 3  4]]]


**Summary**

* np.fliplr(): Flips the array left-to-right, reversing the order of columns.

* np.flipud(): Flips the array up-to-down, reversing the order of rows.

# **9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?**

The array_split() method in NumPy is a powerful function used to split an array into multiple sub-arrays. It is particularly useful for dividing arrays into chunks when working with large datasets or when you need to partition data for batch processing.

### **Functionality of array_split()**

The array_split() function divides an array into multiple sub-arrays based on specified criteria. Here’s a breakdown of its functionality and how it handles uneven splits:

**Syntax: numpy.array_split(ary, indices_or_sections, axis=0)**

* ary: The input array to be split.
* indices_or_sections: Determines how the array is split. It can be:
  * An integer: The number of equal-sized chunks to return.
  * A 1-D array of sorted integers: Specifies the indices at which to split the array.
  * A list of integers: Specifies the indices at which to split the array.
axis: The axis along which to split the array. The default is 0 (rows).

**Handling Uneven Splits**

When the number of elements in the array cannot be evenly divided by the specified number of sections, array_split() handles the uneven splits by distributing the extra elements as evenly as possible among the resulting sub-arrays.

**Key Points**:

**Even Number of Sections: **If the number of sections evenly divides the array, all sub-arrays will be of equal size.

**Uneven Number of Sections:** If the array cannot be evenly divided, the resulting sub-arrays will differ in size, with some sub-arrays having one more element than others.

Examples

**1. Splitting an Array into a Fixed Number of Chunks:**

Example:

In [20]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split into 3 equal chunks
chunks = np.array_split(arr, 3)

print("Chunks after splitting into 3 parts:")
for chunk in chunks:
    print(chunk)


Chunks after splitting into 3 parts:
[1 2 3]
[4 5 6]
[7 8 9]


**2. Splitting an Array into a Fixed Number of Chunks (Uneven Split):**

Example:

In [21]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Split into 4 chunks
chunks = np.array_split(arr, 4)

print("Chunks after splitting into 4 parts:")
for chunk in chunks:
    print(chunk)



Chunks after splitting into 4 parts:
[1 2 3]
[4 5 6]
[7 8]
[ 9 10]


 **3. Splitting an Array by Specified Indices**:

Example:



In [22]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split by indices [2, 5]
chunks = np.array_split(arr, [2, 5])

print("Chunks after splitting by indices [2, 5]:")
for chunk in chunks:
    print(chunk)


Chunks after splitting by indices [2, 5]:
[1 2]
[3 4 5]
[6 7 8 9]


**Summary**

* Functionality: array_split() divides an array into multiple sub-arrays based on specified criteria (number of chunks or split indices).
* Handling Uneven Splits: When dividing an array into chunks that cannot evenly divide the array, array_split() distributes the extra elements as evenly as possible among the resulting sub-arrays. This ensures that the chunks are as equal as possible, with some having one more element than others if necessary.
* Flexibility: array_split() can handle arrays of any dimensionality and provides flexibility in splitting arrays either by specifying the number of chunks or by specific split indices.

# **10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?**

In NumPy, vectorization and broadcasting are key concepts that significantly enhance the efficiency and performance of array operations. They enable NumPy to perform operations on arrays in a highly optimized manner, minimizing the need for explicit loops and leveraging low-level optimizations. Here’s a detailed explanation of each concept and how they contribute to efficient array operations:

## **Vectorization**

**Concept**: Vectorization refers to the process of converting operations that would traditionally be performed in a loop into a form that can be executed simultaneously over entire arrays or vectors. This is achieved by using NumPy's built-in operations, which are implemented in compiled code (typically C or Fortran), allowing for fast execution.

**How It Works:**

Element-wise Operations: NumPy allows operations to be applied element-wise to arrays. For example, adding two arrays or multiplying an array by a scalar.
Optimized Implementations: These operations are performed using highly optimized routines that take advantage of hardware-level parallelism and efficient memory access patterns.
Example:

python

In [24]:
import numpy as np

# Create two large arrays
arr1 = np.random.rand(1000000)
arr2 = np.random.rand(1000000)

# Vectorized operation: element-wise addition
result = arr1 + arr2
print(result)

[1.33193709 0.23315745 1.39137812 ... 0.95008961 0.5930574  1.30141975]


In this example, adding arr1 and arr2 is performed element-wise in a vectorized manner. This is much faster than iterating through the arrays with a loop due to the underlying C implementations and hardware optimizations.

## **Broadcasting**
Concept: Broadcasting is a technique used to perform operations on arrays of different shapes in a way that makes them compatible for element-wise operations. It allows NumPy to handle arrays with different dimensions and sizes without explicitly reshaping them.

**How It Works:**

Rules: Broadcasting works by aligning the shapes of arrays according to certain rules:
If the arrays have different numbers of dimensions, the smaller array is padded with ones on the left side until both arrays have the same number of dimensions.
The arrays are then compared element-wise from the last dimension to the first. If the dimensions are not the same, the smaller array is broadcasted to match the shape of the larger array.

**Broadcasted Dimensions:**

 If dimensions are different but compatible (i.e., one is 1 or the same), the smaller dimension is stretched to match the larger dimension.
Example:

In [25]:
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Create a 1D array
arr_1d = np.array([10, 20, 30])

# Broadcast arr_1d to the shape of arr_2d
result = arr_2d + arr_1d

print("Result of broadcasting:")
print(result)


Result of broadcasting:
[[11 22 33]
 [14 25 36]]


**Contributions to Efficient Array Operations**

**1. Performance Optimization:**

* Vectorization: Eliminates the need for explicit loops in Python, which are slower due to Python's interpreted nature. Operations are performed in compiled code, making them much faster and leveraging parallel processing capabilities of modern CPUs.
* Broadcasting: Avoids the need to manually reshape arrays or create large intermediate arrays to perform operations. It handles arrays of different shapes efficiently, reducing memory overhead and improving performance.

**2. Code Simplicity:**

* Vectorization: Leads to cleaner, more readable code by removing explicit loops and using concise array operations.
* Broadcasting: Simplifies the code needed to perform operations on arrays of different shapes, reducing the complexity of managing array dimensions.

**3. Memory Efficiency:**

* Vectorization: Reduces the need for creating intermediate arrays and handles operations directly on the existing arrays.
* Broadcasting: Avoids the creation of large temporary arrays by efficiently aligning and operating on arrays with different shapes.
**Summary**
* Vectorization: Converts operations into a form that can be performed simultaneously over entire arrays, utilizing optimized, compiled routines for faster execution.
* Broadcasting: Allows operations on arrays of different shapes by aligning them according to specific rules, thus simplifying code and improving efficiency without needing manual reshaping.
* Both vectorization and broadcasting are essential for efficient numerical computing with NumPy, enabling fast, scalable, and readable array operations while leveraging low-level optimizations and reducing memory overhead.

# **PRACTICAL QUESTIONS**

## **1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**

In [26]:
import numpy as np

# Step 1: Create a 3x3 array with random integers between 1 and 100
np.random.seed(0)  # For reproducibility
arr = np.random.randint(1, 101, size=(3, 3))

print("Original Array:")
print(arr)

# Step 2: Interchange rows and columns (Transpose the array)
transposed_arr = arr.T

print("\nTransposed Array (Rows and Columns Interchanged):")
print(transposed_arr)


Original Array:
[[45 48 65]
 [68 68 10]
 [84 22 37]]

Transposed Array (Rows and Columns Interchanged):
[[45 68 84]
 [48 68 22]
 [65 10 37]]


## **2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array**

In [27]:
import numpy as np

# Step 1: Create a 1D array with 10 elements
array_1d = np.arange(10)  # This will generate an array [0, 1, 2, ..., 9]

print("Original 1D Array:")
print(array_1d)

# Step 2: Reshape the 1D array into a 2x5 array
array_2x5 = array_1d.reshape((2, 5))

print("\nReshaped to 2x5 Array:")
print(array_2x5)

# Step 3: Reshape the 2x5 array into a 5x2 array
array_5x2 = array_2x5.reshape((5, 2))

print("\nReshaped to 5x2 Array:")
print(array_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## **3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array**

In [28]:
import numpy as np

# Step 1: Create a 4x4 array with random float values
np.random.seed(0)  # For reproducibility
array_4x4 = np.random.rand(4, 4)

print("Original 4x4 Array:")
print(array_4x4)

# Step 2: Add a border of zeros around the 4x4 array to make it 6x6
# np.pad() is used to add padding
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("\n6x6 Array with Border of Zeros:")
print(array_6x6)


Original 4x4 Array:
[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.5488135  0.71518937 0.60276338 0.54488318 0.        ]
 [0.         0.4236548  0.64589411 0.43758721 0.891773   0.        ]
 [0.         0.96366276 0.38344152 0.79172504 0.52889492 0.        ]
 [0.         0.56804456 0.92559664 0.07103606 0.0871293  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


## **4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.**

In [29]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 65, 5)

print("Array of integers from 10 to 60 with a step of 5:")
print(array)


Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


## **5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.**

In [30]:
import numpy as np

# Step 1: Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Step 2: Apply different case transformations

# Uppercase
uppercase_array = np.char.upper(string_array)

# Lowercase (although strings are already in lowercase, this demonstrates the transformation)
lowercase_array = np.char.lower(string_array)

# Title Case
titlecase_array = np.char.title(string_array)

# Capitalize (first character uppercase, rest lowercase)
capitalize_array = np.char.capitalize(string_array)

# Print results
print("Original Array:")
print(string_array)

print("\nUppercase:")
print(uppercase_array)

print("\nLowercase:")
print(lowercase_array)

print("\nTitle Case:")
print(titlecase_array)

print("\nCapitalize:")
print(capitalize_array)


Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalize:
['Python' 'Numpy' 'Pandas']


#**6. Generate a NumPy array of words. Insert a space between each character of every word in the Array**

In [31]:
import numpy as np

# Step 1: Create a NumPy array of words
words_array = np.array(['apple', 'banana', 'cherry'])

# Step 2: Insert a space between each character of every word
words_with_spaces = np.char.join(' ', words_array)

# Print results
print("Original Array of Words:")
print(words_array)

print("\nWords with Spaces Between Characters:")
print(words_with_spaces)


Original Array of Words:
['apple' 'banana' 'cherry']

Words with Spaces Between Characters:
['a p p l e' 'b a n a n a' 'c h e r r y']


# **7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

In [32]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10, 20, 30], [40, 50, 60]])

# Element-wise addition
addition_result = array1 + array2

# Element-wise subtraction
subtraction_result = array1 - array2

# Element-wise multiplication
multiplication_result = array1 * array2

# Element-wise division
division_result = array1 / array2

# Print results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition_result)

print("\nElement-wise Subtraction:")
print(subtraction_result)

print("\nElement-wise Multiplication:")
print(multiplication_result)

print("\nElement-wise Division:")
print(division_result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[10 20 30]
 [40 50 60]]

Element-wise Addition:
[[11 22 33]
 [44 55 66]]

Element-wise Subtraction:
[[ -9 -18 -27]
 [-36 -45 -54]]

Element-wise Multiplication:
[[ 10  40  90]
 [160 250 360]]

Element-wise Division:
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


# **8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**

In [33]:
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(identity_matrix)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


# **9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.**

In [34]:
import numpy as np

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
np.random.seed(0)  # For reproducibility
random_array = np.random.randint(0, 1000, size=100)

print("Random Array:")
print(random_array)

# Step 2: Define a function to check if a number is prime
def is_prime(n):
    """Return True if n is a prime number, else False."""
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# Step 3: Find and display all prime numbers in the array
primes = [num for num in random_array if is_prime(num)]

print("\nPrime Numbers in the Array:")
print(primes)


Random Array:
[684 559 629 192 835 763 707 359   9 723 277 754 804 599  70 472 600 396
 314 705 486 551  87 174 600 849 677 537 845  72 777 916 115 976 755 709
 847 431 448 850  99 984 177 755 797 659 147 910 423 288 961 265 697 639
 544 543 714 244 151 675 510 459 882 183  28 802 128 128 932  53 901 550
 488 756 273 335 388 617  42 442 543 888 257 321 999 937  57 291 870 119
 779 430  82  91 896 398 611 565 908 633]

Prime Numbers in the Array:
[359, 277, 599, 677, 709, 431, 797, 659, 151, 53, 617, 257, 937]


# **10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.**

In [36]:
import numpy as np

# Step 1: Create a NumPy array representing daily temperatures for a month
# Assuming 30 days of temperatures (for simplicity, use random values between -10 and 35 degrees Celsius)
np.random.seed(0)  # For reproducibility
daily_temperatures = np.random.randint(-10, 36, size=30)

print("Daily Temperatures for the Month:")
print(daily_temperatures)

# Step 2: Reshape the array to group temperatures by weeks
# There are 4 weeks and 2 extra days (if considering a month with 30 days)
weekly_temperatures = daily_temperatures.reshape(5,6)

# Step 3: Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures for the Month:
[ 34 -10  -7  -7  29  -1   9  11  26  13  -4  14  14   2  -9  28  29  13
  14   7  27  15   3  -2  -1  10   6  -5   5 -10]

Weekly Averages:
[ 6.33333333 11.5        12.83333333 10.66666667  0.83333333]
